# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath D:/modeltech64_10.4/win64
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/FPGACode/HDLBitsSht/HDLBitsSht.cache/wt [current_project]
set_property parent.project_path E:/FPGACode/HDLBitsSht/HDLBitsSht.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  E:/FPGACode/HDLBitsSht/HDLBitsSht.srcs/sources_1/new/Popcount3.v
  E:/FPGACode/HDLBitsSht/HDLBitsSht.srcs/sources_1/new/Wire_decl.v
  E:/FPGACode/HDLBitsSht/HDLBitsSht.srcs/sources_1/new/Vectorr.v
  E:/FPGACode/HDLBitsSht/HDLBitsSht.srcs/sources_1/new/Vectorgates.v
  E:/FPGACode/HDLBitsSht/HDLBitsSht.srcs/sources_1/new/Vector3.v
  E:/FPGACode/HDLBitsSht/HDLBitsSht.srcs/sources_1/new/Vector2.v
  E:/FPGACode/HDLBitsSht/HDLBitsSht.srcs/sources_1/new/Vector1.v
  E:/FPGACode/HDLBitsSht/HDLBitsSht.srcs/sources_1/new/Vector0.v
  E:/FPGACode/HDLBitsSht/HDLBitsSht.srcs/sources_1/new/Gates4.v
  E:/FPGACode/HDLBitsSht/HDLBitsSht.srcs/sources_1/new/Alwaysblock2.v
  E:/FPGACode/HDLBitsSht/HDLBitsSht.srcs/sources_1/new/7458Chip.v
}
synth_design -top Popcount3 -part xc7k70tfbv676-1
write_checkpoint -noxdef Popcount3.dcp
catch { report_utilization -file Popcount3_utilization_synth.rpt -pb Popcount3_utilization_synth.pb }
