######################################################################
#
# File name : tb_led_water_wave.do
# Created on: Tue Oct 04 16:24:00 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
